/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadgrupo77.vistas;

import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Matias
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        menubar = new javax.swing.JMenuBar();
        botonalumno = new javax.swing.JMenu();
        formAlumnos = new javax.swing.JMenuItem();
        botonmateria = new javax.swing.JMenu();
        formMateria = new javax.swing.JMenuItem();
        botonadministracion = new javax.swing.JMenu();
        manejoinsc = new javax.swing.JMenuItem();
        maniNotas = new javax.swing.JMenuItem();
        botonconsultas = new javax.swing.JMenu();
        alumnoporMaterias = new javax.swing.JMenuItem();
        botonsalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        botonalumno.setText("ALUMNO");

        formAlumnos.setText("Formulario Alumno");
        formAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formAlumnosActionPerformed(evt);
            }
        });
        botonalumno.add(formAlumnos);

        menubar.add(botonalumno);

        botonmateria.setText("MATERIA");

        formMateria.setText("Formulario Materia");
        formMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formMateriaActionPerformed(evt);
            }
        });
        botonmateria.add(formMateria);

        menubar.add(botonmateria);

        botonadministracion.setText("ADMINISTRACION");

        manejoinsc.setText("Manejo de Inscripciones");
        manejoinsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manejoinscActionPerformed(evt);
            }
        });
        botonadministracion.add(manejoinsc);

        maniNotas.setText("Manipulacion de Notas");
        maniNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maniNotasActionPerformed(evt);
            }
        });
        botonadministracion.add(maniNotas);

        menubar.add(botonadministracion);

        botonconsultas.setText("CONSULTAS");

        alumnoporMaterias.setText("Alumnos por Materia");
        alumnoporMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoporMateriasActionPerformed(evt);
            }
        });
        botonconsultas.add(alumnoporMaterias);

        menubar.add(botonconsultas);

        botonsalir.setText("SALIR");
        botonsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonsalirMouseClicked(evt);
            }
        });
        menubar.add(botonsalir);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maniNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maniNotasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        CargadeNotas cnv = new CargadeNotas();
        cnv.setVisible(true);
        escritorio.add(cnv);
    }//GEN-LAST:event_maniNotasActionPerformed

    private void formAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioAlumno fav = new FormularioAlumno();
        fav.setVisible(true);
        escritorio.add(fav);

    }//GEN-LAST:event_formAlumnosActionPerformed

    private void formMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioMateria fmv = new FormularioMateria();
        fmv.setVisible(true);
        escritorio.add(fmv);
    }//GEN-LAST:event_formMateriaActionPerformed

    private void manejoinscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manejoinscActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioInscripcion fiv = new FormularioInscripcion();
        fiv.setVisible(true);
        escritorio.add(fiv);
    }//GEN-LAST:event_manejoinscActionPerformed

    private void alumnoporMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoporMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListadoporMateria lamv = new ListadoporMateria();
        lamv.setVisible(true);
        escritorio.add(lamv);
    }//GEN-LAST:event_alumnoporMateriasActionPerformed

    private void botonsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonsalirMouseClicked
         System.exit(0);
    }//GEN-LAST:event_botonsalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alumnoporMaterias;
    private javax.swing.JMenu botonadministracion;
    private javax.swing.JMenu botonalumno;
    private javax.swing.JMenu botonconsultas;
    private javax.swing.JMenu botonmateria;
    private javax.swing.JMenu botonsalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem formAlumnos;
    private javax.swing.JMenuItem formMateria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem manejoinsc;
    private javax.swing.JMenuItem maniNotas;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables
}
